#!/bin/bash

set -e

echo
echo "##################################"
echo "#  Na jaký počítač instalujete?  #"
echo "#  Zbook = 1                     #"
echo "#  Probook = 2                   #"
echo "#  Mirantb = 3                   #"
echo "##################################"

while true; do
    read -r -n 1 -p " Vyberte 1/2/3: " answer
    case $answer in
        [1]* ) echo
               echo "####################################"
               echo "#                                  #"
               echo "#  Zvolili jste Zbook...           #"
               echo "#                                  #"
               echo "####################################"
               echo
               sleep 4 
               break;;
        [2]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Zvolili jste Probook...           #"
               echo "#                                    #"
               echo "######################################"
               echo
               sleep 4 
               break;;
        [3]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Zvolili jste Mirantb...           #"
               echo "#                                    #"
               echo "######################################"
               echo
               sleep 4
               break;;
         * ) echo "Vyberte 1, 2, nebo 3";;
     esac
done

echo
echo "####################"
echo "#  Instalace Niri  #"
echo "####################"
sleep 2

mkdir -p $HOME/.local/src
cd $HOME/.local/src
sudo apt -y install \
    git libxcb-cursor-dev rustup gcc clang \
    libudev-dev libgbm-dev libxkbcommon-dev libegl1-mesa-dev \
    libwayland-dev libinput-dev libdbus-1-dev libsystemd-dev \
    libseat-dev libpipewire-0.3-dev libpango1.0-dev libdisplay-info-dev

rustup default stable
cargo install cargo-deb

git clone https://github.com/YaLTeR/niri.git
cd niri
cargo deb
sudo apt -y install ./target/debian/*.deb

cd ..
git clone https://github.com/Supreeeme/xwayland-satellite.git
cd xwayland-satellite
cargo deb
sudo apt -y install ./target/debian/*.deb

echo
echo "######################"
echo "# Instalace balíčků  #"
echo "######################"
sleep 2
sudo apt -y install \
    brightnessctl btop cliphist evince fastfetch fd-find ffmpeg \
    firewall-applet firewalld fish font-manager fonts-jetbrains-mono foot fzf \
    galculator gawk geany gparted gvfs hplip-gui imagemagick jq \
    libnotify-bin libreoffice libreoffice-gnome libreoffice-l10n-cs libxcb-cursor-dev libxkbcommon-dev \
    mako-notifier nemo network-manager-applet nfs-common  nwg-look \
    pamixer papirus-icon-theme pavucontrol power-profiles-daemon qt6ct qutebrowser \
    resvg ripgrep ristretto \
    simple-scan swaybg swayidle swaylock system-config-printer \
    udiskie udisks2 vainfo \
    waybar wget wireplumber wl-clipboard wlsunset \
    youtubedl-gui zenity zoxide 

cd $HOME
mkdir Dokumenty Videa Hudba Stažené Templates

while true; do
    case $answer in
        [1]* ) echo
               echo "####################################"
               echo "#                                  #"
               echo "#  Probíhá konfigurace Zbook...    #"
               echo "#                                  #"
               echo "####################################"
               # sudo xbps-install -S nvidia
               git clone --bare -b debian https://github.com/lrestj/zbook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               bash $HOME/.local/bin/bravedeb
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/zbook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/zbook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
        [2]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Probook...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare -b debian https://github.com/lrestj/probook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
        [3]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Mirantb...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare -b debian https://github.com/lrestj/probook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
         * ) echo "Vyberte 1, 2, nebo 3";;
     esac
done

git clone https://github.com/lrestj/install $HOME/.dotfiles/install/
cd $HOME/.dotfiles/install/
git config --global user.email "rest@seznam.cz"
git config --global user.name "LrestJ"
git remote remove origin
git remote add github git@github.com:lrestj/install.git
git remote add gitlab git@gitlab.com:lrestj/install.git
git remote -v

echo    
echo "#########################"
echo "#  Autologin & firewall #"
echo "#########################"
sudo cp -rf $HOME/.dotfiles/getty@tty1.service.d /etc/systemd/system/
sudo systemctl enable firewalld.service

echo
echo "###########################"
echo "#  Nfs Synology settings  #"
echo "###########################"
sudo cp -v /etc/fstab /etc/fstab.bak
cat $HOME/.dotfiles/nfs2fstab.txt | sudo tee -a /etc/fstab >> /dev/null

echo
echo "###################"
echo "#  Grub settings  #"
echo "###################"
sudo sed -i '11iGRUB_THEME=/home/libor/.dotfiles/TelaGrubTheme/theme.txt' /etc/default/grub
sudo cp -fv $HOME/.dotfiles/40_custom /etc/grub.d/
sudo update-grub


echo
echo "#################################"
echo "#  Instalace balíčků ze zdroje  #"
echo "#################################"
echo
sleep 1
bash $HOME/.local/bin/pkgsbuild

echo
echo "########################"
echo "#  NetworkManager fix  #"
echo "########################"
echo
sleep 1
sudo sed -i 's/managed=false/managed=true/g' /etc/NetworkManager/NetworkManager.conf
sudo rm -r /etc/network/
sudo apt -y remove ifupdown 

echo
echo "#####################"
echo "#  Konec instalace  #"
echo "#####################"
echo
echo "####################################"
echo "#  Restartovat do nového systému?  #"
echo "####################################"
while true; do
    read -r -n 1 -p "Vyberte (A/N): " answer
    case $answer in
        [Aa]* ) echo -e "\n Restartuji..."
                sleep 1
                sudo reboot; break;;
        [Nn]* ) exit;;
        * ) echo -e "\nVyberte A nebo N.";;
    esac
done

###  END OF FILE  ###
