#!/bin/bash

echo "############################"
echo "#                          #"
echo "#  Spouštím instalaci...   #"
echo "#                          #"
echo "############################"
echo ".cfg.git" >> .gitignore &&

echo
echo "##################################"
echo "#  Na jaký počítač instalujete?  #"
echo "#  Zbook = 1                     #"
echo "#  Probook = 2                   #"
echo "#  Mirantb = 3                   #"
echo "##################################"

while true; do
    read -r -n 1 -p " Vyberte 1/2/3: " answer
    case $answer in
        [1]* ) echo
               echo "####################################"
               echo "#                                  #"
               echo "#  Probíhá konfigurace Zbook...    #"
               echo "#                                  #"
               echo "####################################"
               git clone --bare https://github.com/lrestj/nixos.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               cp -fv /etc/nixos/hardware-configuration.nix $HOME/.dotfiles/nixos/hosts/zbook/ 
               sudo nixos-rebuild switch --flake $HOME/.dotfiles/nixos#zbook 
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/nixos.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/nixos.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
        [2]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Probook...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare https://github.com/lrestj/probook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               cp -fv /etc/nixos/hardware-configuration.nix $HOME/.dotfiles/nixos/hosts/probook/ 
               sudo nixos-rebuild switch --flake $HOME/.dotfiles/nixos#probook
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
        [3]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Mirantb...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare https://github.com/lrestj/mirantb.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               cp -fv /etc/nixos/hardware-configuration.nix $HOME/.dotfiles/nixos/hosts/mirantb/ 
               sudo nixos-rebuild switch --flake $HOME/.dotfiles/nixos#mirantb
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               break;;
         * ) echo "Vyberte 1, 2, nebo 3";;
     esac
done
  
mkdir Dokumenty Videa Hudba Stažené Public Templates

echo -e "\n"
echo "############################"
echo "#                          #" 
echo "#  Konec instalace         #" 
echo "#  Lze smazat /etc/nixos/  #" 
echo "#                          #" 
echo "############################"
echo

while true; do
    read -r -n 1 -p "Restartovat do nové konfigurace? (A/N): " answer
    case $answer in
        [Aa]* ) echo -e "\n Restartuji..."
                sleep 1
                systemctl reboot; break;;
        [Nn]* ) exit;;
        * ) echo -e "\nVyberte A nebo N.";;
    esac
done

##### END OF FILE #####
