#!/bin/bash

set -e

echo
echo "##################################"
echo "#  Na jaký počítač instalujete?  #"
echo "#  Zbook = 1                     #"
echo "#  Probook = 2                   #"
echo "#  Mirantb = 3                   #"
echo "##################################"

while true; do
    read -r -n 1 -p " Vyberte 1/2/3: " answer
    case $answer in
        [1]* ) echo
               echo "###########################"
               echo "#                         #"
               echo "#  Zvolili jste Zbook...  #"
               echo "#                         #"
               echo "###########################"
               echo
               sleep 4 
               break;;
        [2]* ) echo
               echo "#############################"
               echo "#                           #"
               echo "#  Zvolili jste Probook...  #"
               echo "#                           #"
               echo "#############################"
               echo
               sleep 4 
               break;;
        [3]* ) echo
               echo "#############################"
               echo "#                           #"
               echo "#  Zvolili jste Mirantb...  #"
               echo "#                           #"
               echo "#############################"
               echo
               sleep 4
               break;;
         * ) echo "Vyberte 1, 2, nebo 3";;
     esac
done

echo "##########################"
echo "#  Instalace balíčků...  #"
echo "##########################"
# Add repo for Brave
printf "repository=https://github.com/sofijacom/void-package/releases/latest/download/\n" | sudo tee /etc/xbps.d/sofijacom-void-repository.conf

sudo xbps-install -S
sudo xbps-install -S void-repo-nonfree  &&
sudo xbps-install -S intel-ucode

# Installing pkgs
sudo xbps-install -S \
7zip alsa-pipewire autofs baobab brave-browser brightnessctl btop base-devel \
chrony cliphist cryptsetup dconf-editor dialog elogind evince exfatprogs \
fastfetch fd file-roller fish-shell fontmanager foot fuzzel fzf \
galculator gcolor3 geany glxinfo gparted gufw gvfs \
hplip-gui hunspell-cs hunspell-en intel-video-accel \
jq libreoffice-calc libreoffice-writer libreoffice-gnome libreoffice-i18n-cs \
libva-utils linux-headers lvm2 mako mdadm mesa-intel-dri mpv \
ncurses-devel nemo nemo-fileroller network-manager-applet nfs-utils \
niri noto-fonts-emoji noto-fonts-ttf nwg-look \
pamixer papirus-icon-theme pavucontrol pipewire power-profiles-daemon \
qt5-wayland qt6-wayland qt6ct qutebrowser qytdl resvg ristretto \
simple-scan snooze swaybg swayidle swaylock tmux tumbler terminus-font \
udiskie unzip vim vlc void-live-audio \
Waybar wayland-devel wayland-protocols wlsunset xdg-desktop-portal-gnome \
xdg-desktop-portal-gtk xeyes xdg-user-dirs xfce-polkit xhost xmirror \
xournalpp xtools xwayland-satellite xz yazi zenity zip

    case $answer in
        [1]* ) echo
               echo "####################################"
               echo "#                                  #"
               echo "#  Probíhá konfigurace Zbook...    #"
               echo "#                                  #"
               echo "####################################"
               sudo xbps-install -S nvidia580
               git clone --bare -b void https://github.com/lrestj/zbook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/zbook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/zbook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               ;;
        [2]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Probook...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare -b void https://github.com/lrestj/probook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/probook.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               ;;
        [3]* ) echo
               echo "######################################"
               echo "#                                    #"
               echo "#  Probíhá konfigurace Mirantb...    #"
               echo "#                                    #"
               echo "######################################"
               git clone --bare -b void https://github.com/lrestj/probook.git $HOME/.cfg.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME checkout -f &&
               echo
               echo "###################################"
               echo "#  Konfigurace git repozitáře...  #"
               echo "###################################"
               git config --global user.email "rest@seznam.cz"
               git config --global user.name "LrestJ"
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote remove origin
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add github git@github.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote add gitlab git@gitlab.com:lrestj/mirantb.git
               git --git-dir=$HOME/.cfg.git/ --work-tree=$HOME remote -v
               ;;
         * ) exit 1;;
     esac
 
echo "###########################"
echo "#  Konfigurace služeb...  #"
echo "###########################"
sudo mkdir -p /etc/pipewire/pipewire.conf.d
sudo ln -s /usr/share/examples/wireplumber/10-wireplumber.conf /etc/pipewire/pipewire.conf.d/
sudo mkdir -p /etc/pipewire/pipewire.conf.d
sudo ln -s /usr/share/examples/pipewire/20-pipewire-pulse.conf /etc/pipewire/pipewire.conf.d/
sudo mkdir -p /etc/sysctl.d
echo vm.swappiness=10 | sudo tee /etc/sysctl.d/99-swappiness.conf
sudo cp -rfv $HOME/.dotfiles/autofs /etc/
sudo ln -s /etc/sv/ufw /var/service/
sudo ln -s /etc/sv/autofs /var/service/
sudo ln -s /etc/sv/NetworkManager /var/service/
sudo rm /var/service/dhcpcd
sudo ln -s /etc/sv/power-profiles-daemon /var/service/
sudo ln -s /etc/sv/snooze-daily /var/service/
sudo ln -s /etc/sv/snooze-weekly /var/service/
sudo ln -s /etc/sv/cupsd /var/service/
sudo ln -s /etc/sv/dbus /var/service/
sudo ln -s /etc/sv/chronyd /var/service/
sudo powerprofilesctl set performance
sudo sed -i -e 's/FONT=.*/FONT=ter-222b/g' /etc/rc.conf

# Fstrim
sudo mkdir -p /etc/cron.weekly
sudo cp -v $HOME/.local/bin/fstrimdo /etc/cron.weekly/

mkdir -p Dokumenty Videa Hudba Stažené Templates

git clone https://github.com/lrestj/install $HOME/.dotfiles/install/
cd $HOME/.dotfiles/install/
git config --global user.email "rest@seznam.cz"
git config --global user.name "LrestJ"
git remote remove origin
git remote add github git@github.com:lrestj/install.git
git remote add gitlab git@gitlab.com:lrestj/install.git
git remote -v

echo
echo "###############################"
echo "#                             #"
echo "#  Grub settings & Vim build  #"
echo "#                             #"
echo "###############################"
sudo sed -i '11iGRUB_THEME=/home/libor/.dotfiles/voidGrubTheme/theme.txt' /etc/default/grub
sudo update-grub
bash vimbuild

echo
echo "############################"
echo "#  Po dokončení instalace  #" 
echo "#  přepni na tty2          #"
echo "#  a spusť autologiVoid    #" 
echo "############################"
echo
sleep 7
bash $HOME/.local/bin/inreconf

### END OF FILE ###
